version: '3'

services:
  msemployee:
    image: wzapps/msemployee:latest
    build:
      context: .
    ports:
      - "5000:80"
    environment:
        AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
        AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
        AZURE_TENANT_ID: ${AZURE_TENANT_ID}
        AZURE_KEY_VAULT: ${AZURE_KEY_VAULT}
